# Change these first
owner: pletos-esports # Your GitHub organization or username, where this repository lives
repo: pletos-uptime # The name of this repository

sites:
  - name: Pletos API
    url: https://api.pletos.gg/status
  - name: Pletos Website
    url: https://www.pletos.gg
  - name: Pletos Partners
    url: https://partners.pletos.gg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pletos.gg
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/65513541
  name: Pletos
  introTitle: "**Pletos** allows you to safely predict esports matches with your friends."
  introMessage: This is a status page allowing you to check whether our services are up and running or not.
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/FQUQUDu
    - title: Website
      href: https://www.pletos.gg/

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
